Web/Controllers/PortfolioItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Core_Portfolio.Entities;
using Infrastructure_Portfolio;
using Web.Models;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Core_Portfolio.Interface;
using Microsoft.AspNetCore.Http;

namespace Web.Controllers
{
    public class PortfolioItemsController : Controller
    {
        private readonly IUnitOfWork<PortfolioItem> _portfolio;
        private readonly IHostingEnvironment _hosting;
        private DataContext _Context { get; set; }

        public PortfolioItemsController(IUnitOfWork<PortfolioItem> portfolio, IHostingEnvironment hosting, DataContext _Context)
        {
            _portfolio = portfolio;
            _hosting = hosting;
            this._Context = _Context;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(ULogin log)
        {

            
            Personal emp = _Context.Personal.FirstOrDefault(a=>a.Profile.Equals(log.Email) && a.Avatar.Equals(log.Password));

            if (emp != null)
            {
                HttpContext.Session.SetString("email", emp.Profile);
                HttpContext.Session.SetString("name", emp.FullName);
                return RedirectToAction("Index","Home");
            }
            ViewBag.Error = "Invalid Email / Password";
            return View(log);
        }

        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }




        [HttpGet]
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("name") == null)
                return RedirectToAction("Login");

            return View(_portfolio.Entity.GetAll());
        }

        [HttpPost]
        public IActionResult Index(string SearchKey)
        {
            if(HttpContext.Session.GetString("name") == null)
                return RedirectToAction("Login");

            var items = _Context.PortfolioItem.Where(a => a.ProjectName.Contains(SearchKey)).ToList();
            
            return View(items);
        }

        //___________________Start Main functions______________________//

        [HttpGet]
        public IActionResult Details(Guid? id)
        {
            if (HttpContext.Session.GetString("name") == null)
                return RedirectToAction("Login");

          

            if (id == null)
            {
                return NotFound();
            }

            var portfolioItem = _portfolio.Entity.GetById(id);
            if (portfolioItem == null)
            {
                return NotFound();
            }

            return View(portfolioItem);
        }

        [HttpGet]
        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("name") == null)
                return RedirectToAction("Login");
            if (!HttpContext.Session.GetString("email").Equals("moh@gmail.com"))
                return RedirectToAction("Login");

            return View();
        }
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PortfolioViewModel model)
        {
            if (HttpContext.Session.GetString("name") == null)
                return RedirectToAction("Login");

            if (!HttpContext.Session.GetString("email").Equals("moh@gmail.com"))
                return RedirectToAction("Login");

            if (ModelState.IsValid)
            {
                if (model.File != null)
                {
                    string uploads = Path.Combine(_hosting.WebRootPath, @"img\portfolio");
                    string fullPath = Path.Combine(uploads, model.File.FileName);
                    model.File.CopyTo(new FileStream(fullPath, FileMode.Create));
                }

                PortfolioItem portfolioItem = new PortfolioItem
                {
                    ProjectName = model.ProjectName,
                    Description = model.Description,
                    ImageUrl = model.File.FileName
                };

                _portfolio.Entity.Insert(portfolioItem);
               
                _portfolio.Save();
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(Guid? id)
        {
            if (HttpContext.Session.GetString("name") == null)
                return RedirectToAction("Login");

            if (!HttpContext.Session.GetString("email").Equals("moh@gmail.com"))
                return RedirectToAction("Login");

            if (id == null)
            {
                return NotFound();
            }

            var portfolioItem = _portfolio.Entity.GetById(id);
            if (portfolioItem == null)
            {
                return NotFound();
            }

            PortfolioViewModel portfolioViewModel = new PortfolioViewModel
            {
                Id = portfolioItem.Id,
                Description = portfolioItem.Description,
                ImageUrl = portfolioItem.ImageUrl,
                ProjectName = portfolioItem.ProjectName
            };

            return View(portfolioViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Guid id, PortfolioViewModel model)
        {
            if (HttpContext.Session.GetString("name") == null)
                return RedirectToAction("Login");

            if (!HttpContext.Session.GetString("email").Equals("moh@gmail.com"))
                return RedirectToAction("Login");

            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (model.File != null)
                    {
                        string uploads = Path.Combine(_hosting.WebRootPath, @"img\portfolio");
                        string fullPath = Path.Combine(uploads, model.File.FileName);
                        model.File.CopyTo(new FileStream(fullPath, FileMode.Create));
                    }

                    PortfolioItem portfolioItem = new PortfolioItem
                    {

                        Id = model.Id,
                        ProjectName = model.ProjectName,
                        Description = model.Description,
                        ImageUrl = model.File.FileName
                    };

                    _portfolio.Entity.Update(portfolioItem);
                    _portfolio.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PortfolioItemExists(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Delete(Guid? id)
        {
            if (HttpContext.Session.GetString("name") == null)
                return RedirectToAction("Login");

            if (!HttpContext.Session.GetString("email").Equals("moh@gmail.com"))
                return RedirectToAction("Login");

            if (id == null)
            {
                return NotFound();
            }

            var portfolioItem = _portfolio.Entity.GetById(id);
            if (portfolioItem == null)
            {
                return NotFound();
            }

            return View(portfolioItem);
        }

        // POST: PortfolioItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            if (HttpContext.Session.GetString("name") == null)
                return RedirectToAction("Login");

            if (!HttpContext.Session.GetString("email").Equals("moh@gmail.com"))
                return RedirectToAction("Login");

            _portfolio.Entity.Delete(id);
            _portfolio.Save();
            return RedirectToAction(nameof(Index));
        }

        private bool PortfolioItemExists(Guid id)
        {

            return _portfolio.Entity.GetAll().Any(e => e.Id == id);
        }
    }
}

Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Portfolio - LUA</title>
    <!-- Custom fonts for this theme -->
    <link href="~/fonts/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">


    <!-- Theme CSS -->
    <link href="~/css/freelancer.css" rel="stylesheet">
    <style>

        .search {
            width: 80%;
            position: relative;
            
            top:-20px;
        }

    .searchTerm {
        width: 80%;
        border: 3px solid #5e54b3;
        border-right: none;
        padding: 15px;
        height: 35px;
        border-radius: 5px 0 0 5px;
        outline: none;
        color: #9DBFAF;
    }
    .searchTerm:focus {
            color: #5e54b3;
        }
    .searchButton {
            width: 35px;
            height: 36px;
            border: 1px solid #00B4CC;
            background: #5e54b3;
            text-align: center;
            color: #ffffff;
            border-radius: 0 5px 5px 0;
            cursor: pointer;
            font-size: 20px;
        }
    .list{
        position:relative;
        top:9px;
    }


    </style>
</head>

<body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="/home">LUA-Portfolio</a>
            <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">

                    <!--  <!--Start Serach
      <li class="list">
          <form asp-action="Search" asp-controller="SearchController" method="get">
              <input type="text" class="searchTerm" placeholder="Search project name" name="SearchKey">
              <button type="submit" class="searchButton">
                  <i class="fa fa-search"></i>
          </form>

      </li> -->
                    <!--End Serach-->
                    <!--Start Project-->
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="/PortfolioItems/Index">Projects</a>
                    </li>
                    <!--End Project-->
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="/home/Index">Portfolio</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#about">About</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#contact">Contact</a>
                    </li>

                    <li class="btn btn-light">
                        @if (Context.Session.GetString("name") != null)
                        {
                             <a asp-controller="PortfolioItems" asp-action="Logout" class="nav-link"><span id="Lgin">Welcome @Context.Session.GetString("name")</span></a>
                        }
                        else
                        {
                            <a asp-controller="PortfolioItems" asp-action="Login" class="nav-link"><span id="Lgin">Login</span></a>
                        }
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Render Body -->
    <div>
        @RenderBody()
    </div>
    <!-- Footer -->
    <footer class="footer text-center">
        <div class="container">
            <div class="row">

                <!-- Footer Location -->
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Location</h4>
                    <p class="lead mb-0">
                        Palestine-Jenin
                        <br>Arab American University
                    </p>
                </div>

                <!-- Footer Social Icons -->
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Around the Web</h4>
                    <a class="btn btn-outline-light btn-social mx-1" href="#">
                        <i class="fab fa-fw fa-facebook-f"></i>
                    </a>
                    <a class="btn btn-outline-light btn-social mx-1" href="#">
                        <i class="fab fa-fw fa-twitter"></i>
                    </a>
                    <a class="btn btn-outline-light btn-social mx-1" href="#">
                        <i class="fab fa-fw fa-linkedin-in"></i>
                    </a>
                    <a class="btn btn-outline-light btn-social mx-1" href="#">
                        <i class="fab fa-fw fa-dribbble"></i>
                    </a>
                </div>

                <!-- Footer About Text -->
                <div class="col-lg-4">
                    <h4 class="text-uppercase mb-4">About Projects</h4>
                    <p class="lead mb-0">Prototypes, Digital Products (Apps, Websites, SaaS solutions) and design systems which are visually pleasing, user-centric and easy to use.</p>
                </div>

            </div>
        </div>
    </footer>

    <!-- Copyright Section -->
    <section class="copyright py-4 text-center text-white">
        <div class="container">
            <small> &copy; 2022 LUA PORTFOLIO</small>
        </div>
    </section>

    <!-- Bootstrap core JavaScript -->
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="~/js/jquery.easing.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="~/js/freelancer.min.js"></script>
</body>

</html>